// Line data for the live map. Positions are schematic (before spacing is applied).
// The route runs from Hammersmith, round the loop clockwise and back to Edgware Road, where trains double back.
// PAD2 and ERC2 are second icons for the second visit to Paddington and Edgware Road: no label, dotted link to the real station (see "of").
window.UNDERCURRENT_LINE = {
 "id": "circle", "name": "Circle", "api": "circle",
 "colour": {"light": "#FFD300", "dark": "#FFE14D"},
 "train": {"light": "#8A6F00", "dark": "#FFF4B8"},
 "dirs": {
  "S": {"label": "Clockwise", "stat": "Clockwise", "platform": ["eastbound", "outer rail"]},
  "N": {"label": "Anticlockwise", "stat": "Anticlockwise", "platform": ["westbound", "inner rail"]}
 },
 "spacing": 1.3,
 "labelFromDir": true,
 "stations": [
  {"id": "ERC", "naptan": "940GZZLUERC", "code": "ERD", "name": "Edgware Road", "x": 96.7, "y": 0, "pref": "top", "lines": ["Edgware", "Road"]},
  {"id": "BST", "naptan": "940GZZLUBST", "code": "BST", "name": "Baker Street", "x": 193.3, "y": 0, "pref": "top", "lines": ["Baker", "Street"]},
  {"id": "GPS", "naptan": "940GZZLUGPS", "code": "GPS", "name": "Great Portland Street", "x": 290.0, "y": 0, "pref": "top", "lines": ["Great Portland", "Street"]},
  {"id": "ESQ", "naptan": "940GZZLUESQ", "code": "ESQ", "name": "Euston Square", "x": 386.7, "y": 0, "pref": "top", "lines": ["Euston", "Square"]},
  {"id": "KSX", "naptan": "940GZZLUKSX", "code": "KGX", "name": "King's Cross St Pancras", "x": 483.3, "y": 0, "pref": "top", "lines": ["King's Cross", "St Pancras"]},
  {"id": "FCN", "naptan": "940GZZLUFCN", "code": "FAR", "name": "Farringdon", "x": 580.0, "y": 0, "pref": "top"},
  {"id": "BBN", "naptan": "940GZZLUBBN", "code": "BBN", "name": "Barbican", "x": 676.7, "y": 0, "pref": "top"},
  {"id": "MGT", "naptan": "940GZZLUMGT", "code": "MOG", "name": "Moorgate", "x": 773.3, "y": 0, "pref": "top"},
  {"id": "LVT", "naptan": "940GZZLULVT", "code": "LST", "name": "Liverpool Street", "x": 870.0, "y": 0, "pref": "top", "lines": ["Liverpool", "Street"]},
  {"id": "ALD", "naptan": "940GZZLUALD", "code": "ALD", "name": "Aldgate", "x": 930, "y": 60, "pref": "left"},
  {"id": "TWH", "naptan": "940GZZLUTWH", "code": "TWH", "name": "Tower Hill", "x": 930, "y": 180, "pref": "left"},
  {"id": "MMT", "naptan": "940GZZLUMMT", "code": "MON", "name": "Monument", "x": 930, "y": 300, "pref": "left"},
  {"id": "CST", "naptan": "940GZZLUCST", "code": "CST", "name": "Cannon Street", "x": 870, "y": 360, "pref": "top", "lines": ["Cannon", "Street"]},
  {"id": "MSH", "naptan": "940GZZLUMSH", "code": "MSH", "name": "Mansion House", "x": 783, "y": 360, "pref": "top", "lines": ["Mansion", "House"]},
  {"id": "BKF", "naptan": "940GZZLUBKF", "code": "BKF", "name": "Blackfriars", "x": 696, "y": 360, "pref": "top"},
  {"id": "TMP", "naptan": "940GZZLUTMP", "code": "TMP", "name": "Temple", "x": 609, "y": 360, "pref": "top"},
  {"id": "EMB", "naptan": "940GZZLUEMB", "code": "EMB", "name": "Embankment", "x": 522, "y": 360, "pref": "top"},
  {"id": "WSM", "naptan": "940GZZLUWSM", "code": "WMR", "name": "Westminster", "x": 435, "y": 360, "pref": "top"},
  {"id": "SJP", "naptan": "940GZZLUSJP", "code": "SJP", "name": "St. James's Park", "x": 348, "y": 360, "pref": "top", "lines": ["St. James's", "Park"]},
  {"id": "VIC", "naptan": "940GZZLUVIC", "code": "VIC", "name": "Victoria", "x": 261, "y": 360, "pref": "top"},
  {"id": "SSQ", "naptan": "940GZZLUSSQ", "code": "SSQ", "name": "Sloane Square", "x": 174, "y": 360, "pref": "top", "lines": ["Sloane", "Square"]},
  {"id": "SKS", "naptan": "940GZZLUSKS", "code": "SKN", "name": "South Kensington", "x": 87, "y": 360, "pref": "top", "lines": ["South", "Kensington"]},
  {"id": "GTR", "naptan": "940GZZLUGTR", "code": "GRD", "name": "Gloucester Road", "x": 0, "y": 360, "pref": "left", "lines": ["Gloucester", "Road"]},
  {"id": "HSK", "naptan": "940GZZLUHSK", "code": "HSK", "name": "High Street Kensington", "x": -80, "y": 280, "pref": "right"},
  {"id": "NHG", "naptan": "940GZZLUNHG", "code": "NHG", "name": "Notting Hill Gate", "x": -80, "y": 200, "pref": "right"},
  {"id": "BWT", "naptan": "940GZZLUBWT", "code": "BWT", "name": "Bayswater", "x": -80, "y": 120, "pref": "right"},
  {"id": "PAD", "naptan": "940GZZLUPAH", "code": "PAD", "name": "Paddington", "x": 0, "y": 0, "pref": "top", "alias": ["940GZZLUPAC"]},
  {"id": "RYO", "naptan": "940GZZLURYO", "code": "ROK", "name": "Royal Oak", "x": -80, "y": 0, "pref": "top", "lines": ["Royal", "Oak"]},
  {"id": "WSP", "naptan": "940GZZLUWSP", "code": "WSP", "name": "Westbourne Park", "x": -160, "y": 0, "pref": "top", "lines": ["Westbourne", "Park"]},
  {"id": "LAD", "naptan": "940GZZLULAD", "code": "LGV", "name": "Ladbroke Grove", "x": -220, "y": 60, "pref": "left"},
  {"id": "LRD", "naptan": "940GZZLULRD", "code": "LRD", "name": "Latimer Road", "x": -280, "y": 120, "pref": "left"},
  {"id": "WLA", "naptan": "940GZZLUWLA", "code": "WLA", "name": "Wood Lane", "x": -340, "y": 180, "pref": "right"},
  {"id": "SBM", "naptan": "940GZZLUSBM", "code": "SBM", "name": "Shepherd's Bush Market", "x": -340, "y": 260, "pref": "right"},
  {"id": "GHK", "naptan": "940GZZLUGHK", "code": "GHR", "name": "Goldhawk Road", "x": -340, "y": 340, "pref": "right"},
  {"id": "HSC", "naptan": "940GZZLUHSC", "code": "HMS", "name": "Hammersmith", "x": -340, "y": 420, "pref": "right"},
  {"id": "PAD2", "naptan": "940GZZLUPAC", "code": "PAD", "name": "Paddington", "x": 0, "y": 40, "pref": "top", "of": "PAD"},
  {"id": "ERC2", "naptan": "940GZZLUERC", "code": "ERD", "name": "Edgware Road", "x": 96.7, "y": 40, "pref": "top", "of": "ERC"}
 ],
 "routes": [
  ["HSC", "GHK", "SBM", "WLA", "LRD", "LAD", "WSP", "RYO", "PAD", "ERC", "BST", "GPS", "ESQ", "KSX", "FCN", "BBN", "MGT", "LVT", "ALD", "TWH", "MMT", "CST", "MSH", "BKF", "TMP", "EMB", "WSM", "SJP", "VIC", "SSQ", "SKS", "GTR", "HSK", "NHG", "BWT", "PAD2", "ERC2"]
 ],
 "ix": {
  "HSC": ["hammersmith", "district", "piccadilly"],
  "GHK": ["hammersmith"],
  "SBM": ["hammersmith"],
  "WLA": ["hammersmith"],
  "LRD": ["hammersmith"],
  "LAD": ["hammersmith"],
  "WSP": ["hammersmith"],
  "RYO": ["hammersmith"],
  "PAD": ["bakerloo", "district", "elizabeth", "hammersmith", "rail"],
  "ERC": ["district", "hammersmith"],
  "BST": ["bakerloo", "hammersmith", "jubilee", "metropolitan"],
  "GPS": ["hammersmith", "metropolitan"],
  "ESQ": ["hammersmith", "metropolitan"],
  "KSX": ["hammersmith", "metropolitan", "northern", "piccadilly", "victoria", "rail"],
  "FCN": ["hammersmith", "metropolitan", "elizabeth", "rail"],
  "BBN": ["hammersmith", "metropolitan"],
  "MGT": ["hammersmith", "metropolitan", "northern", "elizabeth", "rail"],
  "LVT": ["central", "hammersmith", "metropolitan", "elizabeth", "weaver", "rail"],
  "ALD": ["metropolitan"],
  "TWH": ["district", "dlr"],
  "MMT": ["central", "northern", "waterloo", "dlr"],
  "CST": ["district", "rail"],
  "MSH": ["district"],
  "BKF": ["district", "rail"],
  "TMP": ["district"],
  "EMB": ["bakerloo", "district", "northern"],
  "WSM": ["district", "jubilee"],
  "SJP": ["district"],
  "VIC": ["district", "victoria", "rail"],
  "SSQ": ["district"],
  "SKS": ["district", "piccadilly"],
  "GTR": ["district", "piccadilly"],
  "HSK": ["district"],
  "NHG": ["central", "district"],
  "BWT": ["district"]
 },
 "emptyAt": [560, 300],
 "river": {"x": -780, "y": -200, "scale": 1.05, "width": 44, "label": [1160, 610]},
 "facts": [
  {"tag": "History", "text": "The Circle line was completed in 1884 as the Inner Circle, joining up the Metropolitan and District railways."},
  {"tag": "History", "text": "The Circle only became a line of its own on the Tube map in 1949."},
  {"tag": "History", "text": "Since December 2009 Circle trains no longer go round and round: they run from Hammersmith round the loop to Edgware Road, then double back."},
  {"tag": "Stations", "text": "The Circle has no stations of its own: every one is shared with the District, Metropolitan or Hammersmith & City lines."},
  {"tag": "Stations", "text": "King's Cross St Pancras is one of the busiest stations on the Underground, with six Tube lines."},
  {"tag": "Stations", "text": "Edgware Road (Circle Line) is a different station from the Bakerloo line's Edgware Road, a short walk away."},
  {"tag": "Stations", "text": "Hammersmith has two Underground stations. The Circle and Hammersmith & City lines use the one by the Broadway shops."},
  {"tag": "Trains", "text": "The Circle shares tracks with the District, Metropolitan and Hammersmith & City lines for its whole length."},
  {"tag": "Trains", "text": "The line is served by S7 Stock trains, which are air-conditioned and open from end to end."},
  {"tag": "Trains", "text": "On the Tube map the Circle is yellow, and in the early days of the Underground the whole loop was a single service."}
 ]
};
