// Line data for the live map. Positions are schematic (before spacing is applied).
window.UNDERCURRENT_LINE = {
 "id": "district", "name": "District", "api": "district",
 "colour": {"light": "#00782A", "dark": "#2FA85A"},
 "train": {"light": "#0A4D22", "dark": "#C9F0D6"},
 "dirs": {
  "S": {"label": "Eastbound", "stat": "Eastbound", "platform": ["eastbound"]},
  "N": {"label": "Westbound", "stat": "Westbound", "platform": ["westbound"]}
 },
 "spacing": 1.3,
 "stations": [
  {"id": "EBY", "naptan": "940GZZLUEBY", "code": "EBY", "name": "Ealing Broadway", "x": -720, "y": -240, "pref": "left"},
  {"id": "ECM", "naptan": "940GZZLUECM", "code": "ECO", "name": "Ealing Common", "x": -660, "y": -180, "pref": "left"},
  {"id": "ACT", "naptan": "940GZZLUACT", "code": "ACT", "name": "Acton Town", "x": -600, "y": -120, "pref": "left"},
  {"id": "CWP", "naptan": "940GZZLUCWP", "code": "CWP", "name": "Chiswick Park", "x": -540, "y": -60, "pref": "top", "lines": ["Chiswick", "Park"]},
  {"id": "TNG", "naptan": "940GZZLUTNG", "code": "TGR", "name": "Turnham Green", "x": -480, "y": 0, "pref": "left"},
  {"id": "SFB", "naptan": "940GZZLUSFB", "code": "SFB", "name": "Stamford Brook", "x": -400, "y": 0, "pref": "bottom", "lines": ["Stamford", "Brook"]},
  {"id": "RVP", "naptan": "940GZZLURVP", "code": "RVP", "name": "Ravenscourt Park", "x": -320, "y": 0, "pref": "top", "lines": ["Ravenscourt", "Park"]},
  {"id": "HSD", "naptan": "940GZZLUHSD", "code": "HMS", "name": "Hammersmith", "x": -240, "y": 0, "pref": "bottom"},
  {"id": "BSC", "naptan": "940GZZLUBSC", "code": "BCT", "name": "Barons Court", "x": -160, "y": 0, "pref": "top", "lines": ["Barons", "Court"]},
  {"id": "WKN", "naptan": "940GZZLUWKN", "code": "WKN", "name": "West Kensington", "x": -80, "y": 0, "pref": "bottom", "lines": ["West", "Kensington"]},
  {"id": "ECT", "naptan": "940GZZLUECT", "code": "EAR", "name": "Earl's Court", "x": 0, "y": 0, "pref": "bottom", "lines": ["Earl's", "Court"]},
  {"id": "GTR", "naptan": "940GZZLUGTR", "code": "GRD", "name": "Gloucester Road", "x": 160, "y": 0, "pref": "bottom", "lines": ["Gloucester", "Road"]},
  {"id": "SKS", "naptan": "940GZZLUSKS", "code": "SKN", "name": "South Kensington", "x": 240, "y": 0, "pref": "top", "lines": ["South", "Kensington"]},
  {"id": "SSQ", "naptan": "940GZZLUSSQ", "code": "SSQ", "name": "Sloane Square", "x": 300, "y": 60, "pref": "left"},
  {"id": "VIC", "naptan": "940GZZLUVIC", "code": "VIC", "name": "Victoria", "x": 360, "y": 120, "pref": "left"},
  {"id": "SJP", "naptan": "940GZZLUSJP", "code": "SJP", "name": "St. James's Park", "x": 420, "y": 180, "pref": "left"},
  {"id": "WSM", "naptan": "940GZZLUWSM", "code": "WMR", "name": "Westminster", "x": 500, "y": 180, "pref": "top"},
  {"id": "EMB", "naptan": "940GZZLUEMB", "code": "EMB", "name": "Embankment", "x": 580, "y": 180, "pref": "bottom"},
  {"id": "TMP", "naptan": "940GZZLUTMP", "code": "TMP", "name": "Temple", "x": 660, "y": 180, "pref": "top"},
  {"id": "BKF", "naptan": "940GZZLUBKF", "code": "BKF", "name": "Blackfriars", "x": 740, "y": 180, "pref": "bottom"},
  {"id": "MSH", "naptan": "940GZZLUMSH", "code": "MSH", "name": "Mansion House", "x": 820, "y": 180, "pref": "top", "lines": ["Mansion", "House"]},
  {"id": "CST", "naptan": "940GZZLUCST", "code": "CST", "name": "Cannon Street", "x": 900, "y": 180, "pref": "bottom", "lines": ["Cannon", "Street"]},
  {"id": "MMT", "naptan": "940GZZLUMMT", "code": "MON", "name": "Monument", "x": 980, "y": 180, "pref": "top"},
  {"id": "TWH", "naptan": "940GZZLUTWH", "code": "TWH", "name": "Tower Hill", "x": 1060, "y": 180, "pref": "bottom", "lines": ["Tower", "Hill"]},
  {"id": "ADE", "naptan": "940GZZLUADE", "code": "ALE", "name": "Aldgate East", "x": 1120, "y": 120, "pref": "right"},
  {"id": "WPL", "naptan": "940GZZLUWPL", "code": "WCH", "name": "Whitechapel", "x": 1180, "y": 60, "pref": "right"},
  {"id": "SGN", "naptan": "940GZZLUSGN", "code": "SGN", "name": "Stepney Green", "x": 1240, "y": 0, "pref": "right"},
  {"id": "MED", "naptan": "940GZZLUMED", "code": "MLE", "name": "Mile End", "x": 1300, "y": -60, "pref": "right"},
  {"id": "BWR", "naptan": "940GZZLUBWR", "code": "BOW", "name": "Bow Road", "x": 1360, "y": -120, "pref": "right"},
  {"id": "BBB", "naptan": "940GZZLUBBB", "code": "BBB", "name": "Bromley-by-Bow", "x": 1420, "y": -180, "pref": "right"},
  {"id": "WHM", "naptan": "940GZZLUWHM", "code": "WHM", "name": "West Ham", "x": 1480, "y": -240, "pref": "right"},
  {"id": "PLW", "naptan": "940GZZLUPLW", "code": "PLW", "name": "Plaistow", "x": 1540, "y": -300, "pref": "right"},
  {"id": "UPK", "naptan": "940GZZLUUPK", "code": "UPK", "name": "Upton Park", "x": 1600, "y": -360, "pref": "right"},
  {"id": "EHM", "naptan": "940GZZLUEHM", "code": "EHM", "name": "East Ham", "x": 1660, "y": -420, "pref": "right"},
  {"id": "BKG", "naptan": "940GZZLUBKG", "code": "BKG", "name": "Barking", "x": 1740, "y": -420, "pref": "top"},
  {"id": "UPY", "naptan": "940GZZLUUPY", "code": "UPY", "name": "Upney", "x": 1800, "y": -360, "pref": "right"},
  {"id": "BEC", "naptan": "940GZZLUBEC", "code": "BEC", "name": "Becontree", "x": 1800, "y": -280, "pref": "right"},
  {"id": "DGY", "naptan": "940GZZLUDGY", "code": "DGY", "name": "Dagenham Heathway", "x": 1800, "y": -200, "pref": "right"},
  {"id": "DGE", "naptan": "940GZZLUDGE", "code": "DGE", "name": "Dagenham East", "x": 1800, "y": -120, "pref": "right"},
  {"id": "EPK", "naptan": "940GZZLUEPK", "code": "EPK", "name": "Elm Park", "x": 1800, "y": -40, "pref": "right"},
  {"id": "HCH", "naptan": "940GZZLUHCH", "code": "HCH", "name": "Hornchurch", "x": 1800, "y": 40, "pref": "right"},
  {"id": "UPB", "naptan": "940GZZLUUPB", "code": "UPB", "name": "Upminster Bridge", "x": 1800, "y": 120, "pref": "right"},
  {"id": "UPM", "naptan": "940GZZLUUPM", "code": "UPM", "name": "Upminster", "x": 1800, "y": 200, "pref": "right"},
  {"id": "GBY", "naptan": "940GZZLUGBY", "code": "GBY", "name": "Gunnersbury", "x": -560, "y": 80, "pref": "left"},
  {"id": "KWG", "naptan": "940GZZLUKWG", "code": "KWG", "name": "Kew Gardens", "x": -640, "y": 160, "pref": "left"},
  {"id": "RMD", "naptan": "940GZZLURMD", "code": "RMD", "name": "Richmond", "x": -720, "y": 240, "pref": "left"},
  {"id": "WBN", "naptan": "940GZZLUWBN", "code": "WBN", "name": "West Brompton", "x": 0, "y": 160, "pref": "right"},
  {"id": "FBY", "naptan": "940GZZLUFBY", "code": "FBY", "name": "Fulham Broadway", "x": 0, "y": 240, "pref": "right"},
  {"id": "PSG", "naptan": "940GZZLUPSG", "code": "PSG", "name": "Parsons Green", "x": 0, "y": 320, "pref": "right"},
  {"id": "PYB", "naptan": "940GZZLUPYB", "code": "PYB", "name": "Putney Bridge", "x": 0, "y": 440, "pref": "right"},
  {"id": "EPY", "naptan": "940GZZLUEPY", "code": "EPY", "name": "East Putney", "x": 0, "y": 520, "pref": "right"},
  {"id": "SFS", "naptan": "940GZZLUSFS", "code": "SFS", "name": "Southfields", "x": -60, "y": 580, "pref": "left"},
  {"id": "WIP", "naptan": "940GZZLUWIP", "code": "WIP", "name": "Wimbledon Park", "x": -120, "y": 640, "pref": "left"},
  {"id": "WIM", "naptan": "940GZZLUWIM", "code": "WIM", "name": "Wimbledon", "x": -180, "y": 700, "pref": "left"},
  {"id": "KOY", "naptan": "940GZZLUKOY", "code": "KOY", "name": "Kensington (Olympia)", "x": -120, "y": -120, "pref": "left"},
  {"id": "HSK", "naptan": "940GZZLUHSK", "code": "HSK", "name": "High Street Kensington", "x": 0, "y": -160, "pref": "right"},
  {"id": "NHG", "naptan": "940GZZLUNHG", "code": "NHG", "name": "Notting Hill Gate", "x": 60, "y": -220, "pref": "left"},
  {"id": "BWT", "naptan": "940GZZLUBWT", "code": "BWT", "name": "Bayswater", "x": 120, "y": -280, "pref": "left"},
  {"id": "PAC", "naptan": "940GZZLUPAC", "code": "PAD", "name": "Paddington", "x": 180, "y": -340, "pref": "left"},
  {"id": "ERC", "naptan": "940GZZLUERC", "code": "ERD", "name": "Edgware Road", "x": 240, "y": -400, "pref": "right"}
 ],
 "routes": [
  ["EBY", "ECM", "ACT", "CWP", "TNG", "SFB", "RVP", "HSD", "BSC", "WKN", "ECT", "GTR", "SKS", "SSQ", "VIC", "SJP", "WSM", "EMB", "TMP", "BKF", "MSH", "CST", "MMT", "TWH", "ADE", "WPL", "SGN", "MED", "BWR", "BBB", "WHM", "PLW", "UPK", "EHM", "BKG", "UPY", "BEC", "DGY", "DGE", "EPK", "HCH", "UPB", "UPM"],
  ["RMD", "KWG", "GBY", "TNG", "SFB", "RVP", "HSD", "BSC", "WKN", "ECT", "GTR", "SKS", "SSQ", "VIC", "SJP", "WSM", "EMB", "TMP", "BKF", "MSH", "CST", "MMT", "TWH", "ADE", "WPL", "SGN", "MED", "BWR", "BBB", "WHM", "PLW", "UPK", "EHM", "BKG", "UPY", "BEC", "DGY", "DGE", "EPK", "HCH", "UPB", "UPM"],
  ["WIM", "WIP", "SFS", "EPY", "PYB", "PSG", "FBY", "WBN", "ECT", "GTR", "SKS", "SSQ", "VIC", "SJP", "WSM", "EMB", "TMP", "BKF", "MSH", "CST", "MMT", "TWH", "ADE", "WPL", "SGN", "MED", "BWR", "BBB", "WHM", "PLW", "UPK", "EHM", "BKG", "UPY", "BEC", "DGY", "DGE", "EPK", "HCH", "UPB", "UPM"],
  ["EBY", "ECM", "ACT", "CWP", "TNG", "SFB", "RVP", "HSD", "BSC", "WKN", "ECT", "HSK", "NHG", "BWT", "PAC", "ERC"],
  ["RMD", "KWG", "GBY", "TNG", "SFB", "RVP", "HSD", "BSC", "WKN", "ECT", "HSK", "NHG", "BWT", "PAC", "ERC"],
  ["WIM", "WIP", "SFS", "EPY", "PYB", "PSG", "FBY", "WBN", "ECT", "HSK", "NHG", "BWT", "PAC", "ERC"],
  ["KOY", "ECT", "HSK", "NHG", "BWT", "PAC", "ERC"]
 ],
 "ix": {
  "EBY": ["central", "elizabeth", "rail"],
  "ECM": ["piccadilly"],
  "ACT": ["piccadilly"],
  "TNG": ["piccadilly"],
  "HSD": ["hammersmith", "piccadilly"],
  "BSC": ["piccadilly"],
  "ECT": ["piccadilly"],
  "GTR": ["circle", "piccadilly"],
  "SKS": ["circle", "piccadilly"],
  "SSQ": ["circle"],
  "VIC": ["circle", "victoria", "rail"],
  "SJP": ["circle"],
  "WSM": ["circle", "jubilee"],
  "EMB": ["bakerloo", "circle", "northern"],
  "TMP": ["circle"],
  "BKF": ["circle", "rail"],
  "MSH": ["circle"],
  "CST": ["circle", "rail"],
  "MMT": ["central", "northern", "waterloo", "dlr"],
  "TWH": ["circle", "dlr"],
  "ADE": ["hammersmith"],
  "WPL": ["hammersmith", "elizabeth", "windrush"],
  "SGN": ["hammersmith"],
  "MED": ["central", "hammersmith"],
  "BWR": ["hammersmith"],
  "BBB": ["hammersmith"],
  "WHM": ["hammersmith", "jubilee", "dlr", "rail"],
  "PLW": ["hammersmith"],
  "UPK": ["hammersmith"],
  "EHM": ["hammersmith"],
  "BKG": ["hammersmith", "suffragette", "rail"],
  "UPM": ["rail"],
  "RMD": ["mildmay", "rail"],
  "KWG": ["mildmay", "rail"],
  "GBY": ["mildmay", "rail"],
  "WIM": ["rail"],
  "WBN": ["mildmay"],
  "KOY": ["mildmay", "rail"],
  "HSK": ["circle"],
  "NHG": ["central", "circle"],
  "BWT": ["circle"],
  "PAC": ["bakerloo", "circle", "elizabeth", "hammersmith", "rail"],
  "ERC": ["circle", "hammersmith"]
 },
 "emptyAt": [700, 350],
 "river": {"x": -780, "y": -230, "scale": 1.0, "width": 44, "label": [1100, 610]},
 "facts": [
  {"tag": "History", "text": "The Metropolitan District Railway opened between South Kensington and Westminster in December 1868, and the line has been green on the map ever since."},
  {"tag": "History", "text": "The District line was built to complete the Inner Circle, together with the Metropolitan Railway."},
  {"tag": "History", "text": "Earl's Court had the first escalators on the Underground, installed in 1911."},
  {"tag": "Stations", "text": "With 60 stations, the District line serves more stations than any other Underground line."},
  {"tag": "Stations", "text": "The line has branches to Ealing Broadway, Richmond, Wimbledon, Edgware Road and Upminster."},
  {"tag": "Stations", "text": "Upminster is the eastern end of the line, where it meets c2c trains."},
  {"tag": "Stations", "text": "Wimbledon is the southern end of the line, also served by trams and National Rail."},
  {"tag": "Stations", "text": "Kensington (Olympia) is served by District line trains at weekends and for events at the exhibition centre."},
  {"tag": "Stations", "text": "Several stations on the Wimbledon branch, from Parsons Green to Wimbledon Park, sit in quiet suburban streets and are mostly above ground."},
  {"tag": "Trains", "text": "The line is served by S7 Stock trains, which are air-conditioned and open from end to end."},
  {"tag": "Trains", "text": "The District shares tracks with the Piccadilly line between Acton Town and Barons Court, and with the Hammersmith & City line between Aldgate East and Barking."},
  {"tag": "Trains", "text": "The Circle line shares track with the District line for most of its southern half, between Edgware Road and Tower Hill."}
 ]
};
