// Line data for the live map. Positions are schematic (before spacing is applied).
window.UNDERCURRENT_LINE = {
 "id": "hammersmith", "name": "Hammersmith & City", "api": "hammersmith-city",
 "colour": {"light": "#F3A9BB", "dark": "#F6BCCB"},
 "train": {"light": "#B04A6B", "dark": "#FBE3EA"},
 "dirs": {
  "S": {"label": "Eastbound", "stat": "To Barking", "platform": ["eastbound"]},
  "N": {"label": "Westbound", "stat": "To Hammersmith", "platform": ["westbound"]}
 },
 "spacing": 1.3,
 "stations": [
  {"id": "HSC", "naptan": "940GZZLUHSC", "code": "HMS", "name": "Hammersmith", "x": 0, "y": 560, "pref": "right"},
  {"id": "GHK", "naptan": "940GZZLUGHK", "code": "GHR", "name": "Goldhawk Road", "x": 0, "y": 480, "pref": "right"},
  {"id": "SBM", "naptan": "940GZZLUSBM", "code": "SBM", "name": "Shepherd's Bush Market", "x": 0, "y": 400, "pref": "right"},
  {"id": "WLA", "naptan": "940GZZLUWLA", "code": "WLA", "name": "Wood Lane", "x": 0, "y": 320, "pref": "right"},
  {"id": "LRD", "naptan": "940GZZLULRD", "code": "LRD", "name": "Latimer Road", "x": 60, "y": 260, "pref": "right"},
  {"id": "LAD", "naptan": "940GZZLULAD", "code": "LGV", "name": "Ladbroke Grove", "x": 120, "y": 200, "pref": "right"},
  {"id": "WSP", "naptan": "940GZZLUWSP", "code": "WSP", "name": "Westbourne Park", "x": 180, "y": 140, "pref": "top", "lines": ["Westbourne", "Park"]},
  {"id": "RYO", "naptan": "940GZZLURYO", "code": "ROK", "name": "Royal Oak", "x": 260, "y": 140, "pref": "bottom"},
  {"id": "PAH", "naptan": "940GZZLUPAH", "code": "PAC", "name": "Paddington", "x": 340, "y": 140, "pref": "top"},
  {"id": "ERC", "naptan": "940GZZLUERC", "code": "ERD", "name": "Edgware Road", "x": 420, "y": 140, "pref": "bottom", "lines": ["Edgware", "Road"]},
  {"id": "BST", "naptan": "940GZZLUBST", "code": "BST", "name": "Baker Street", "x": 500, "y": 140, "pref": "top", "lines": ["Baker", "Street"]},
  {"id": "GPS", "naptan": "940GZZLUGPS", "code": "GPS", "name": "Great Portland Street", "x": 580, "y": 140, "pref": "bottom", "lines": ["Great Portland", "Street"]},
  {"id": "ESQ", "naptan": "940GZZLUESQ", "code": "ESQ", "name": "Euston Square", "x": 660, "y": 140, "pref": "top", "lines": ["Euston", "Square"]},
  {"id": "KSX", "naptan": "940GZZLUKSX", "code": "KGX", "name": "King's Cross St Pancras", "x": 740, "y": 140, "pref": "bottom", "lines": ["King's Cross", "St Pancras"]},
  {"id": "FCN", "naptan": "940GZZLUFCN", "code": "FAR", "name": "Farringdon", "x": 820, "y": 140, "pref": "top"},
  {"id": "BBN", "naptan": "940GZZLUBBN", "code": "BBN", "name": "Barbican", "x": 900, "y": 140, "pref": "bottom"},
  {"id": "MGT", "naptan": "940GZZLUMGT", "code": "MOG", "name": "Moorgate", "x": 980, "y": 140, "pref": "top"},
  {"id": "LVT", "naptan": "940GZZLULVT", "code": "LST", "name": "Liverpool Street", "x": 1060, "y": 140, "pref": "bottom", "lines": ["Liverpool", "Street"]},
  {"id": "ADE", "naptan": "940GZZLUADE", "code": "ALE", "name": "Aldgate East", "x": 1140, "y": 140, "pref": "top", "lines": ["Aldgate", "East"]},
  {"id": "WPL", "naptan": "940GZZLUWPL", "code": "WCH", "name": "Whitechapel", "x": 1220, "y": 140, "pref": "bottom"},
  {"id": "SGN", "naptan": "940GZZLUSGN", "code": "SGN", "name": "Stepney Green", "x": 1300, "y": 140, "pref": "top", "lines": ["Stepney", "Green"]},
  {"id": "MED", "naptan": "940GZZLUMED", "code": "MLE", "name": "Mile End", "x": 1380, "y": 140, "pref": "bottom", "lines": ["Mile", "End"]},
  {"id": "BWR", "naptan": "940GZZLUBWR", "code": "BOW", "name": "Bow Road", "x": 1460, "y": 140, "pref": "top", "lines": ["Bow", "Road"]},
  {"id": "BBB", "naptan": "940GZZLUBBB", "code": "BBB", "name": "Bromley-by-Bow", "x": 1540, "y": 140, "pref": "bottom", "lines": ["Bromley-", "by-Bow"]},
  {"id": "WHM", "naptan": "940GZZLUWHM", "code": "WHM", "name": "West Ham", "x": 1620, "y": 140, "pref": "top", "lines": ["West", "Ham"]},
  {"id": "PLW", "naptan": "940GZZLUPLW", "code": "PLW", "name": "Plaistow", "x": 1680, "y": 80, "pref": "bottom"},
  {"id": "UPK", "naptan": "940GZZLUUPK", "code": "UPK", "name": "Upton Park", "x": 1760, "y": 80, "pref": "top", "lines": ["Upton", "Park"]},
  {"id": "EHM", "naptan": "940GZZLUEHM", "code": "EHM", "name": "East Ham", "x": 1840, "y": 80, "pref": "bottom", "lines": ["East", "Ham"]},
  {"id": "BKG", "naptan": "940GZZLUBKG", "code": "BKG", "name": "Barking", "x": 1920, "y": 80, "pref": "top"}
 ],
 "routes": [["HSC", "GHK", "SBM", "WLA", "LRD", "LAD", "WSP", "RYO", "PAH", "ERC", "BST", "GPS", "ESQ", "KSX", "FCN", "BBN", "MGT", "LVT", "ADE", "WPL", "SGN", "MED", "BWR", "BBB", "WHM", "PLW", "UPK", "EHM", "BKG"]],
 "ix": {
  "HSC": ["circle", "district", "piccadilly"],
  "GHK": ["circle"],
  "SBM": ["circle"],
  "WLA": ["circle"],
  "LRD": ["circle"],
  "LAD": ["circle"],
  "WSP": ["circle"],
  "RYO": ["circle"],
  "PAH": ["bakerloo", "circle", "district", "elizabeth", "rail"],
  "ERC": ["circle", "district"],
  "BST": ["bakerloo", "circle", "jubilee", "metropolitan"],
  "GPS": ["circle", "metropolitan"],
  "ESQ": ["circle", "metropolitan"],
  "KSX": ["circle", "metropolitan", "northern", "piccadilly", "victoria", "rail"],
  "FCN": ["circle", "metropolitan", "elizabeth", "rail"],
  "BBN": ["circle", "metropolitan"],
  "MGT": ["circle", "metropolitan", "northern", "elizabeth", "rail"],
  "LVT": ["central", "circle", "metropolitan", "elizabeth", "weaver", "rail"],
  "ADE": ["district"],
  "WPL": ["district", "elizabeth", "windrush"],
  "SGN": ["district"],
  "MED": ["central", "district"],
  "BWR": ["district"],
  "BBB": ["district"],
  "WHM": ["district", "jubilee", "dlr", "rail"],
  "PLW": ["district"],
  "UPK": ["district"],
  "EHM": ["district"],
  "BKG": ["district", "suffragette", "rail"]
 },
 "emptyAt": [1250, 350],
 "river": {"x": 100, "y": -90, "scale": 1, "width": 44, "label": [1250, 520]},
 "facts": [
  {"tag": "History", "text": "The Hammersmith & City Railway opened between Paddington and Hammersmith on 13 June 1864, just over a year after the Metropolitan Railway opened."},
  {"tag": "History", "text": "The line was run by the Metropolitan Railway and the Great Western Railway together for many years."},
  {"tag": "History", "text": "The Hammersmith & City line was only shown as a separate line on the Tube map in 1990. Before that it was part of the Metropolitan line."},
  {"tag": "History", "text": "Its pink colour on the map is often described as salmon pink."},
  {"tag": "Stations", "text": "Wood Lane station opened in 2008 to serve the Westfield London shopping centre."},
  {"tag": "Stations", "text": "The Hammersmith & City station at Hammersmith is separate from the District and Piccadilly line station, a short walk away."},
  {"tag": "Stations", "text": "Whitechapel became an interchange with the Elizabeth line when it opened in 2022."},
  {"tag": "Stations", "text": "Barking is the eastern terminus and is also served by c2c trains and the Suffragette line."},
  {"tag": "Stations", "text": "King's Cross St Pancras is one of the busiest stations on the Underground, with six Tube lines."},
  {"tag": "Trains", "text": "The line shares tracks with the Circle line between Hammersmith and Liverpool Street, and with the District line between Aldgate East and Barking."},
  {"tag": "Trains", "text": "The line is served by S7 Stock trains, which are air-conditioned and open from end to end."},
  {"tag": "Engineering", "text": "The line has 29 stations between Hammersmith and Barking."}
 ]
};
