// Line data for the live map. Positions are schematic (before spacing is applied).
window.UNDERCURRENT_LINE = {
 "id": "jubilee", "name": "Jubilee", "api": "jubilee",
 "colour": {"light": "#8D9296", "dark": "#B4B9BD"},
 "train": {"light": "#4A5055", "dark": "#DADDDF"},
 "dirs": {
  "S": {"label": "Eastbound", "stat": "To Stratford", "platform": ["southbound", "eastbound"]},
  "N": {"label": "Westbound", "stat": "To Stanmore", "platform": ["northbound", "westbound"]}
 },
 "spacing": 1.3,
 "stations": [
  {"id": "STM", "naptan": "940GZZLUSTM", "code": "STA", "name": "Stanmore",          "x": 120, "y": 40, "pref": "right"},
  {"id": "CPK", "naptan": "940GZZLUCPK", "code": "CPK", "name": "Canons Park",       "x": 120, "y": 130, "pref": "right"},
  {"id": "QBY", "naptan": "940GZZLUQBY", "code": "QBY", "name": "Queensbury",        "x": 120, "y": 220, "pref": "right"},
  {"id": "KBY", "naptan": "940GZZLUKBY", "code": "KBY", "name": "Kingsbury",         "x": 120, "y": 310, "pref": "right"},
  {"id": "WYP", "naptan": "940GZZLUWYP", "code": "WPK", "name": "Wembley Park",      "x": 120, "y": 400, "pref": "left", "lines": ["Wembley", "Park"]},
  {"id": "NDN", "naptan": "940GZZLUNDN", "code": "NEA", "name": "Neasden",           "x": 170, "y": 450, "pref": "right"},
  {"id": "DOH", "naptan": "940GZZLUDOH", "code": "DHL", "name": "Dollis Hill",       "x": 220, "y": 500, "pref": "right"},
  {"id": "WIG", "naptan": "940GZZLUWIG", "code": "WLG", "name": "Willesden Green",   "x": 270, "y": 550, "pref": "right", "lines": ["Willesden", "Green"]},
  {"id": "KBN", "naptan": "940GZZLUKBN", "code": "KIL", "name": "Kilburn",           "x": 320, "y": 600, "pref": "right"},
  {"id": "WHP", "naptan": "940GZZLUWHP", "code": "WHD", "name": "West Hampstead",    "x": 370, "y": 650, "pref": "right", "lines": ["West", "Hampstead"]},
  {"id": "FYR", "naptan": "940GZZLUFYR", "code": "FRD", "name": "Finchley Road",     "x": 420, "y": 700, "pref": "right", "lines": ["Finchley", "Road"]},
  {"id": "SWC", "naptan": "940GZZLUSWC", "code": "SWC", "name": "Swiss Cottage",     "x": 420, "y": 790, "pref": "right", "lines": ["Swiss", "Cottage"]},
  {"id": "SJW", "naptan": "940GZZLUSJW", "code": "SJW", "name": "St. John's Wood",   "x": 420, "y": 880, "pref": "right", "lines": ["St. John's", "Wood"]},
  {"id": "BST", "naptan": "940GZZLUBST", "code": "BST", "name": "Baker Street",      "x": 420, "y": 970, "pref": "right", "lines": ["Baker", "Street"]},
  {"id": "BND", "naptan": "940GZZLUBND", "code": "BDS", "name": "Bond Street",       "x": 420, "y": 1060, "pref": "right", "lines": ["Bond", "Street"]},
  {"id": "GPK", "naptan": "940GZZLUGPK", "code": "GPK", "name": "Green Park",        "x": 420, "y": 1130, "pref": "right", "lines": ["Green", "Park"]},
  {"id": "WSM", "naptan": "940GZZLUWSM", "code": "WMR", "name": "Westminster",       "x": 420, "y": 1200, "pref": "left"},
  {"id": "WLO", "naptan": "940GZZLUWLO", "code": "WLO", "name": "Waterloo",          "x": 575, "y": 1200, "pref": "bottom"},
  {"id": "SWK", "naptan": "940GZZLUSWK", "code": "SWK", "name": "Southwark",         "x": 700, "y": 1200, "pref": "bottom"},
  {"id": "LNB", "naptan": "940GZZLULNB", "code": "LBG", "name": "London Bridge",     "x": 825, "y": 1200, "pref": "bottom", "lines": ["London", "Bridge"]},
  {"id": "BMY", "naptan": "940GZZLUBMY", "code": "BMY", "name": "Bermondsey",        "x": 950, "y": 1200, "pref": "bottom"},
  {"id": "CWR", "naptan": "940GZZLUCWR", "code": "CWR", "name": "Canada Water",      "x": 1030, "y": 1280, "pref": "bottom", "lines": ["Canada", "Water"]},
  {"id": "CYF", "naptan": "940GZZLUCYF", "code": "CWF", "name": "Canary Wharf",      "x": 1207, "y": 1280, "pref": "top", "lines": ["Canary", "Wharf"]},
  {"id": "NGW", "naptan": "940GZZLUNGW", "code": "NGW", "name": "North Greenwich",   "x": 1327, "y": 1280, "pref": "bottom", "lines": ["North", "Greenwich"]},
  {"id": "CGT", "naptan": "940GZZLUCGT", "code": "CTN", "name": "Canning Town",      "x": 1327, "y": 1040, "pref": "right", "lines": ["Canning", "Town"]},
  {"id": "WHM", "naptan": "940GZZLUWHM", "code": "WHM", "name": "West Ham",          "x": 1327, "y": 950, "pref": "right"},
  {"id": "STD", "naptan": "940GZZLUSTD", "code": "SFD", "name": "Stratford",         "x": 1327, "y": 860, "pref": "right"}
 ],
 "ix": {
  "WYP": ["metropolitan"], "WHP": ["mildmay", "rail"], "FYR": ["metropolitan"],
  "BST": ["bakerloo", "circle", "hammersmith", "metropolitan"], "BND": ["central", "elizabeth"],
  "GPK": ["piccadilly", "victoria"], "WSM": ["circle", "district"],
  "WLO": ["bakerloo", "northern", "waterloo", "rail"], "LNB": ["northern", "rail"],
  "CWR": ["windrush"], "CYF": ["elizabeth", "dlr"], "CGT": ["dlr"],
  "WHM": ["district", "hammersmith", "dlr", "rail"], "STD": ["central", "elizabeth", "mildmay", "dlr", "rail"]
 },
 "river": {"x": 22.5, "y": 697.5, "scale": 0.75, "width": 44, "label": [1100, 610]},
 "facts": [
  {"tag": "History", "text": "The Jubilee line opened on 1 May 1979 and was named to mark Queen Elizabeth II's Silver Jubilee in 1977."},
  {"tag": "History", "text": "During planning it was known as the Fleet line, after the River Fleet that runs beneath central London."},
  {"tag": "History", "text": "Its grey colour on the map stands for silver, in honour of the Silver Jubilee."},
  {"tag": "History", "text": "Before 1979 the stations from Stanmore to Baker Street were a branch of the Bakerloo line."},
  {"tag": "History", "text": "The Stanmore branch was opened by the Metropolitan Railway in 1932, then handed to the Bakerloo line in 1939."},
  {"tag": "History", "text": "The line originally ended at Charing Cross. Those platforms closed in 1999 when the extension to Stratford opened."},
  {"tag": "Engineering", "text": "The Jubilee Line Extension from Green Park to Stratford opened in stages in 1999, linking Canary Wharf and the Millennium Dome to the network."},
  {"tag": "Engineering", "text": "The underground stations on the extension, from Westminster to North Greenwich, were the first on the Underground with platform edge doors."},
  {"tag": "Engineering", "text": "The Jubilee line is the only Underground line that crosses the Thames four times."},
  {"tag": "Engineering", "text": "Trains have run under automatic train control since 2011, allowing more trains per hour through the central section."},
  {"tag": "Trains", "text": "The line uses 1996 Stock trains, lengthened from six to seven cars in 2006."},
  {"tag": "Design · Canary Wharf", "text": "Canary Wharf station was designed by Foster + Partners, with a vast concourse often compared to a cathedral."},
  {"tag": "Design · Westminster", "text": "Westminster station, by Hopkins Architects, was built alongside Portcullis House, with escalators crossing a deep concrete and steel box."},
  {"tag": "Design · Southwark", "text": "Southwark station's upper concourse has a curved wall of blue glass panels by artist Alexander Beleschenko."},
  {"tag": "Design · North Greenwich", "text": "North Greenwich station was designed by Alsop, Lyall and Störmer, finished in deep blue."},
  {"tag": "Stations", "text": "Wembley Park is the station for Wembley Stadium, and handles huge crowds on event days."},
  {"tag": "Stations", "text": "Stratford is the line's eastern terminus and served the Olympic Park during the London 2012 Games."},
  {"tag": "Stations", "text": "Canning Town is above ground, with Jubilee and DLR platforms side by side."},
  {"tag": "Stations", "text": "Bond Street became an interchange with the Elizabeth line when it opened in 2022."},
  {"tag": "Depots", "text": "Jubilee line trains are maintained at Neasden depot in the west and Stratford Market depot in the east."}
 ]
};
