// Line data for the live map. Positions are schematic (before spacing is applied).
window.UNDERCURRENT_LINE = {
 "id": "metropolitan", "name": "Metropolitan", "api": "metropolitan",
 "colour": {"light": "#9B0056", "dark": "#D6489B"},
 "train": {"light": "#5E0034", "dark": "#F8D6E8"},
 "dirs": {
  "S": {"label": "Inbound", "stat": "To Aldgate", "platform": ["southbound", "eastbound"]},
  "N": {"label": "Outbound", "stat": "From Aldgate", "platform": ["northbound", "westbound"]}
 },
 "spacing": 1.3,
 "stations": [
  {"id": "ALD", "naptan": "940GZZLUALD", "code": "ALD", "name": "Aldgate", "x": 0, "y": 0, "pref": "top"},
  {"id": "LVT", "naptan": "940GZZLULVT", "code": "LST", "name": "Liverpool Street", "x": -80, "y": 0, "pref": "bottom", "lines": ["Liverpool", "Street"]},
  {"id": "MGT", "naptan": "940GZZLUMGT", "code": "MOG", "name": "Moorgate", "x": -160, "y": 0, "pref": "top"},
  {"id": "BBN", "naptan": "940GZZLUBBN", "code": "BBN", "name": "Barbican", "x": -240, "y": 0, "pref": "bottom"},
  {"id": "FCN", "naptan": "940GZZLUFCN", "code": "FAR", "name": "Farringdon", "x": -320, "y": 0, "pref": "top"},
  {"id": "KSX", "naptan": "940GZZLUKSX", "code": "KGX", "name": "King's Cross St Pancras", "x": -400, "y": 0, "pref": "bottom", "lines": ["King's Cross", "St Pancras"]},
  {"id": "ESQ", "naptan": "940GZZLUESQ", "code": "ESQ", "name": "Euston Square", "x": -480, "y": 0, "pref": "top", "lines": ["Euston", "Square"]},
  {"id": "GPS", "naptan": "940GZZLUGPS", "code": "GPS", "name": "Great Portland Street", "x": -560, "y": 0, "pref": "bottom", "lines": ["Great Portland", "Street"]},
  {"id": "BST", "naptan": "940GZZLUBST", "code": "BST", "name": "Baker Street", "x": -640, "y": 0, "pref": "top", "lines": ["Baker", "Street"]},
  {"id": "FYR", "naptan": "940GZZLUFYR", "code": "FYR", "name": "Finchley Road", "x": -700, "y": -60, "pref": "left"},
  {"id": "WYP", "naptan": "940GZZLUWYP", "code": "WPK", "name": "Wembley Park", "x": -760, "y": -120, "pref": "left"},
  {"id": "PRD", "naptan": "940GZZLUPRD", "code": "PRE", "name": "Preston Road", "x": -820, "y": -180, "pref": "left"},
  {"id": "NKP", "naptan": "940GZZLUNKP", "code": "NWP", "name": "Northwick Park", "x": -880, "y": -240, "pref": "left"},
  {"id": "HOH", "naptan": "940GZZLUHOH", "code": "HOH", "name": "Harrow-on-the-Hill", "x": -940, "y": -300, "pref": "right"},
  {"id": "NHA", "naptan": "940GZZLUNHA", "code": "NHA", "name": "North Harrow", "x": -1000, "y": -360, "pref": "left"},
  {"id": "PNR", "naptan": "940GZZLUPNR", "code": "PIN", "name": "Pinner", "x": -1060, "y": -420, "pref": "left"},
  {"id": "NWH", "naptan": "940GZZLUNWH", "code": "NWH", "name": "Northwood Hills", "x": -1120, "y": -480, "pref": "left"},
  {"id": "NOW", "naptan": "940GZZLUNOW", "code": "NOR", "name": "Northwood", "x": -1180, "y": -540, "pref": "left"},
  {"id": "MPK", "naptan": "940GZZLUMPK", "code": "MPK", "name": "Moor Park", "x": -1240, "y": -600, "pref": "right"},
  {"id": "RKW", "naptan": "940GZZLURKW", "code": "RKY", "name": "Rickmansworth", "x": -1300, "y": -540, "pref": "left"},
  {"id": "CYD", "naptan": "940GZZLUCYD", "code": "CHO", "name": "Chorleywood", "x": -1360, "y": -480, "pref": "left"},
  {"id": "CAL", "naptan": "940GZZLUCAL", "code": "CAL", "name": "Chalfont & Latimer", "x": -1420, "y": -420, "pref": "left"},
  {"id": "AMS", "naptan": "940GZZLUAMS", "code": "AMS", "name": "Amersham", "x": -1420, "y": -340, "pref": "left"},
  {"id": "CSM", "naptan": "940GZZLUCSM", "code": "CHM", "name": "Chesham", "x": -1480, "y": -480, "pref": "left"},
  {"id": "CXY", "naptan": "940GZZLUCXY", "code": "CRX", "name": "Croxley", "x": -1300, "y": -660, "pref": "left"},
  {"id": "WAF", "naptan": "940GZZLUWAF", "code": "WAT", "name": "Watford", "x": -1360, "y": -720, "pref": "left"},
  {"id": "WHW", "naptan": "940GZZLUWHW", "code": "WHW", "name": "West Harrow", "x": -1000, "y": -240, "pref": "right"},
  {"id": "RYL", "naptan": "940GZZLURYL", "code": "RAY", "name": "Rayners Lane", "x": -1060, "y": -180, "pref": "right"},
  {"id": "EAE", "naptan": "940GZZLUEAE", "code": "EAS", "name": "Eastcote", "x": -1120, "y": -120, "pref": "right"},
  {"id": "RSM", "naptan": "940GZZLURSM", "code": "RUM", "name": "Ruislip Manor", "x": -1180, "y": -60, "pref": "right"},
  {"id": "RSP", "naptan": "940GZZLURSP", "code": "RUI", "name": "Ruislip", "x": -1240, "y": 0, "pref": "right"},
  {"id": "ICK", "naptan": "940GZZLUICK", "code": "ICK", "name": "Ickenham", "x": -1300, "y": 60, "pref": "right"},
  {"id": "HGD", "naptan": "940GZZLUHGD", "code": "HIL", "name": "Hillingdon", "x": -1360, "y": 120, "pref": "right"},
  {"id": "UXB", "naptan": "940GZZLUUXB", "code": "UXB", "name": "Uxbridge", "x": -1420, "y": 180, "pref": "right"}
 ],
 "routes": [
  ["AMS", "CAL", "CYD", "RKW", "MPK", "NOW", "NWH", "PNR", "NHA", "HOH", "NKP", "PRD", "WYP", "FYR", "BST", "GPS", "ESQ", "KSX", "FCN", "BBN", "MGT", "LVT", "ALD"],
  ["CSM", "CAL", "CYD", "RKW", "MPK", "NOW", "NWH", "PNR", "NHA", "HOH", "NKP", "PRD", "WYP", "FYR", "BST", "GPS", "ESQ", "KSX", "FCN", "BBN", "MGT", "LVT", "ALD"],
  ["WAF", "CXY", "MPK", "NOW", "NWH", "PNR", "NHA", "HOH", "NKP", "PRD", "WYP", "FYR", "BST", "GPS", "ESQ", "KSX", "FCN", "BBN", "MGT", "LVT", "ALD"],
  ["UXB", "HGD", "ICK", "RSP", "RSM", "EAE", "RYL", "WHW", "HOH", "NKP", "PRD", "WYP", "FYR", "BST", "GPS", "ESQ", "KSX", "FCN", "BBN", "MGT", "LVT", "ALD"]
 ],
 "ix": {
  "ALD": ["circle"],
  "LVT": ["central", "circle", "hammersmith", "elizabeth", "weaver", "rail"],
  "MGT": ["circle", "hammersmith", "northern", "elizabeth", "rail"],
  "BBN": ["circle", "hammersmith"],
  "FCN": ["circle", "hammersmith", "elizabeth", "rail"],
  "KSX": ["circle", "hammersmith", "northern", "piccadilly", "victoria", "rail"],
  "ESQ": ["circle", "hammersmith"],
  "GPS": ["circle", "hammersmith"],
  "BST": ["bakerloo", "circle", "hammersmith", "jubilee"],
  "FYR": ["jubilee"],
  "WYP": ["jubilee"],
  "HOH": ["rail"],
  "CYD": ["rail"],
  "CAL": ["rail"],
  "AMS": ["rail"],
  "RYL": ["piccadilly"],
  "EAE": ["piccadilly"],
  "RSM": ["piccadilly"],
  "RSP": ["piccadilly"],
  "ICK": ["piccadilly"],
  "HGD": ["piccadilly"],
  "UXB": ["piccadilly"]
 },
 "emptyAt": [-420, -420],
 "river": {"x": -1560, "y": -360, "scale": 0.85, "width": 44, "label": [1100, 610]},
 "facts": [
  {"tag": "History", "text": "The Metropolitan Railway opened on 10 January 1863 between Paddington and Farringdon, and is the world's first underground passenger railway."},
  {"tag": "History", "text": "The Metropolitan line is the oldest part of the Underground, and Baker Street station has been open since that first day."},
  {"tag": "History", "text": "The Metropolitan Railway coined the name 'Metro-land' to promote the suburbs that grew up along its route."},
  {"tag": "Stations", "text": "Chesham is the northernmost station on the Underground."},
  {"tag": "Stations", "text": "The line has four branches beyond Harrow-on-the-Hill and Moor Park, to Amersham, Chesham, Watford and Uxbridge."},
  {"tag": "Stations", "text": "The Uxbridge branch leaves the main line at Harrow-on-the-Hill and is shared with the Piccadilly line between Rayners Lane and Uxbridge."},
  {"tag": "Stations", "text": "Wembley Park is the station for Wembley Stadium, and is also served by the Jubilee line."},
  {"tag": "Stations", "text": "Baker Street has the Bakerloo, Circle, Hammersmith & City, Jubilee and Metropolitan lines."},
  {"tag": "Trains", "text": "The line shares tracks with the Circle and Hammersmith & City lines between Baker Street and Aldgate."},
  {"tag": "Trains", "text": "The line is served by S8 Stock trains, which are air-conditioned and open from end to end."},
  {"tag": "Trains", "text": "Metropolitan line trains run through the countryside of Hertfordshire and Buckinghamshire, beyond the edge of Greater London."}
 ]
};
