// Station page data: Barbican (Circle, Hammersmith & City and Metropolitan). Generated by tools/make_station.py. Facts: Wikipedia, 'Barbican tube station', fetched 9 Oct 2026.
window.UNDERCURRENT_LINE = {
 "id": "station-bbn",
 "kind": "station",
 "name": "Barbican",
 "naptan": "940GZZLUBBN",
 "lines": {
  "circle": {
   "name": "Circle",
   "colour": {
    "light": "#FFD300",
    "dark": "#FFE14D"
   },
   "train": {
    "light": "#8A6F00",
    "dark": "#FFF4B8"
   },
   "approach": {
    "E": [
     [
      "Latimer Road",
      "Ladbroke Grove",
      "Westbourne Park",
      "Royal Oak",
      "Paddington",
      "Edgware Road",
      "Baker Street",
      "Great Portland Street",
      "Euston Square",
      "King's Cross St Pancras",
      "Farringdon",
      "Barbican"
     ]
    ],
    "W": [
     [
      "Westminster",
      "Embankment",
      "Temple",
      "Blackfriars",
      "Mansion House",
      "Cannon Street",
      "Monument",
      "Tower Hill",
      "Aldgate",
      "Liverpool Street",
      "Moorgate",
      "Barbican"
     ]
    ]
   },
   "short": "CIR",
   "dirs": {
    "E": {
     "label": "Clockwise",
     "platform": [
      "eastbound",
      "outer rail"
     ]
    },
    "W": {
     "label": "Anticlockwise",
     "platform": [
      "westbound",
      "inner rail"
     ]
    }
   }
  },
  "hammersmith-city": {
   "name": "Hammersmith & City",
   "colour": {
    "light": "#F3A9BB",
    "dark": "#F6BCCB"
   },
   "train": {
    "light": "#B04A6B",
    "dark": "#FBE3EA"
   },
   "approach": {
    "E": [
     [
      "Latimer Road",
      "Ladbroke Grove",
      "Westbourne Park",
      "Royal Oak",
      "Paddington",
      "Edgware Road",
      "Baker Street",
      "Great Portland Street",
      "Euston Square",
      "King's Cross St Pancras",
      "Farringdon",
      "Barbican"
     ]
    ],
    "W": [
     [
      "Upton Park",
      "Plaistow",
      "West Ham",
      "Bromley-by-Bow",
      "Bow Road",
      "Mile End",
      "Stepney Green",
      "Whitechapel",
      "Aldgate East",
      "Liverpool Street",
      "Moorgate",
      "Barbican"
     ]
    ]
   },
   "short": "H&C",
   "dirs": {
    "E": {
     "label": "Eastbound",
     "platform": [
      "eastbound"
     ]
    },
    "W": {
     "label": "Westbound",
     "platform": [
      "westbound"
     ]
    }
   }
  },
  "metropolitan": {
   "name": "Metropolitan",
   "colour": {
    "light": "#9B0056",
    "dark": "#D6489B"
   },
   "train": {
    "light": "#5E0034",
    "dark": "#F8D6E8"
   },
   "approach": {
    "E": [
     [
      "North Harrow",
      "Harrow-on-the-Hill",
      "Northwick Park",
      "Preston Road",
      "Wembley Park",
      "Finchley Road",
      "Baker Street",
      "Great Portland Street",
      "Euston Square",
      "King's Cross St Pancras",
      "Farringdon",
      "Barbican"
     ],
     [
      "West Harrow",
      "Harrow-on-the-Hill",
      "Northwick Park",
      "Preston Road",
      "Wembley Park",
      "Finchley Road",
      "Baker Street",
      "Great Portland Street",
      "Euston Square",
      "King's Cross St Pancras",
      "Farringdon",
      "Barbican"
     ]
    ],
    "W": [
     [
      "Aldgate",
      "Liverpool Street",
      "Moorgate",
      "Barbican"
     ]
    ]
   },
   "short": "MET",
   "dirs": {
    "E": {
     "label": "Inbound",
     "platform": [
      "southbound",
      "eastbound"
     ]
    },
    "W": {
     "label": "Outbound",
     "platform": [
      "northbound",
      "westbound"
     ]
    }
   }
  }
 },
 "westWords": "hammersmith|edgware road|baker street|uxbridge|amersham|chesham|watford|harrow|rickmansworth|wembley|paddington",
 "facts": [
  {
   "tag": "History",
   "text": "The station opened on 23 December 1865 as Aldersgate Street, on the extension from Farringdon to Moorgate."
  },
  {
   "tag": "Name",
   "text": "It became Aldersgate in 1910, Aldersgate & Barbican in 1924, and simply Barbican on 1 December 1968."
  },
  {
   "tag": "History",
   "text": "The station was badly bombed in the Blitz, especially in December 1940. Its upper floors were taken down, and the rest of the street building was demolished in 1955."
  },
  {
   "tag": "Poetry",
   "text": "The bomb damage inspired John Betjeman's poem \"Monody on the Death of Aldersgate Station\"."
  },
  {
   "tag": "Design",
   "text": "The platforms are mostly open to the sky. Remains of the structure that once held the station's glass roof can still be seen."
  },
  {
   "tag": "Station",
   "text": "There are four platforms but only two are used: eastbound trains stop at platform 1 and westbound trains at platform 2."
  },
  {
   "tag": "History",
   "text": "The other two platforms served Thameslink trains until March 2009, when they closed so that Farringdon's main line platforms could be lengthened."
  },
  {
   "tag": "Access",
   "text": "Platform 2 is the only step-free platform, with a lift link to the Elizabeth line station at Farringdon, opened in May 2022."
  },
  {
   "tag": "Trivia",
   "text": "The old station building at 134 Aldersgate Street carried a sign saying \"This was Shakespeare's House\", though there is no evidence for it."
  },
  {
   "tag": "Trivia",
   "text": "A plaque at the station remembers Pebbles, the station cat."
  },
  {
   "tag": "Passengers",
   "text": "Barbican recorded about 5.15 million entries and exits in 2024."
  }
 ],
 "tracks": [
  [
   "circle",
   "hammersmith-city",
   "metropolitan"
  ]
 ],
 "angles": [
  -12
 ]
};
