// Station page data: King's Cross St Pancras (Circle, Hammersmith & City, Metropolitan, Northern, Piccadilly and Victoria). Generated by tools/make_station.py. Facts: Wikipedia, 'King's Cross St Pancras tube station', fetched 9 Oct 2026.
window.UNDERCURRENT_LINE = {
 "id": "station-kxc",
 "kind": "station",
 "name": "King's Cross St Pancras",
 "naptan": "940GZZLUKSX",
 "lines": {
  "circle": {
   "name": "Circle",
   "colour": {
    "light": "#FFD300",
    "dark": "#FFE14D"
   },
   "train": {
    "light": "#8A6F00",
    "dark": "#FFF4B8"
   },
   "approach": {
    "E": [
     [
      "Shepherd's Bush Market",
      "Wood Lane",
      "Latimer Road",
      "Ladbroke Grove",
      "Westbourne Park",
      "Royal Oak",
      "Paddington",
      "Edgware Road",
      "Baker Street",
      "Great Portland Street",
      "Euston Square",
      "King's Cross St Pancras"
     ]
    ],
    "W": [
     [
      "Temple",
      "Blackfriars",
      "Mansion House",
      "Cannon Street",
      "Monument",
      "Tower Hill",
      "Aldgate",
      "Liverpool Street",
      "Moorgate",
      "Barbican",
      "Farringdon",
      "King's Cross St Pancras"
     ]
    ]
   },
   "short": "CIR",
   "dirs": {
    "E": {
     "label": "Clockwise",
     "platform": [
      "eastbound",
      "outer rail"
     ]
    },
    "W": {
     "label": "Anticlockwise",
     "platform": [
      "westbound",
      "inner rail"
     ]
    }
   },
   "westWords": "hammersmith|edgware road|baker street|paddington|high street kensington"
  },
  "hammersmith-city": {
   "name": "Hammersmith & City",
   "colour": {
    "light": "#F3A9BB",
    "dark": "#F6BCCB"
   },
   "train": {
    "light": "#B04A6B",
    "dark": "#FBE3EA"
   },
   "approach": {
    "E": [
     [
      "Shepherd's Bush Market",
      "Wood Lane",
      "Latimer Road",
      "Ladbroke Grove",
      "Westbourne Park",
      "Royal Oak",
      "Paddington",
      "Edgware Road",
      "Baker Street",
      "Great Portland Street",
      "Euston Square",
      "King's Cross St Pancras"
     ]
    ],
    "W": [
     [
      "West Ham",
      "Bromley-by-Bow",
      "Bow Road",
      "Mile End",
      "Stepney Green",
      "Whitechapel",
      "Aldgate East",
      "Liverpool Street",
      "Moorgate",
      "Barbican",
      "Farringdon",
      "King's Cross St Pancras"
     ]
    ]
   },
   "short": "H&C",
   "dirs": {
    "E": {
     "label": "Eastbound",
     "platform": [
      "eastbound"
     ]
    },
    "W": {
     "label": "Westbound",
     "platform": [
      "westbound"
     ]
    }
   },
   "westWords": "hammersmith|edgware road|baker street|paddington"
  },
  "metropolitan": {
   "name": "Metropolitan",
   "colour": {
    "light": "#9B0056",
    "dark": "#D6489B"
   },
   "train": {
    "light": "#5E0034",
    "dark": "#F8D6E8"
   },
   "approach": {
    "E": [
     [
      "Northwood Hills",
      "Pinner",
      "North Harrow",
      "Harrow-on-the-Hill",
      "Northwick Park",
      "Preston Road",
      "Wembley Park",
      "Finchley Road",
      "Baker Street",
      "Great Portland Street",
      "Euston Square",
      "King's Cross St Pancras"
     ],
     [
      "Eastcote",
      "Rayners Lane",
      "West Harrow",
      "Harrow-on-the-Hill",
      "Northwick Park",
      "Preston Road",
      "Wembley Park",
      "Finchley Road",
      "Baker Street",
      "Great Portland Street",
      "Euston Square",
      "King's Cross St Pancras"
     ]
    ],
    "W": [
     [
      "Aldgate",
      "Liverpool Street",
      "Moorgate",
      "Barbican",
      "Farringdon",
      "King's Cross St Pancras"
     ]
    ]
   },
   "short": "MET",
   "dirs": {
    "E": {
     "label": "Inbound",
     "platform": [
      "southbound",
      "eastbound"
     ]
    },
    "W": {
     "label": "Outbound",
     "platform": [
      "northbound",
      "westbound"
     ]
    }
   },
   "westWords": "uxbridge|amersham|chesham|watford|harrow|rickmansworth|wembley|baker street"
  },
  "northern": {
   "name": "Northern",
   "colour": {
    "light": "#000000",
    "dark": "#E6E6E6"
   },
   "train": {
    "light": "#6B6B6B",
    "dark": "#A8A8A8"
   },
   "approach": {
    "E": [
     [
      "Edgware",
      "Burnt Oak",
      "Colindale",
      "Hendon Central",
      "Brent Cross",
      "Golders Green",
      "Hampstead",
      "Belsize Park",
      "Chalk Farm",
      "Camden Town",
      "Euston",
      "King's Cross St Pancras"
     ],
     [
      "Totteridge & Whetstone",
      "Woodside Park",
      "West Finchley",
      "Finchley Central",
      "East Finchley",
      "Highgate",
      "Archway",
      "Tufnell Park",
      "Kentish Town",
      "Camden Town",
      "Euston",
      "King's Cross St Pancras"
     ],
     [
      "Mill Hill East",
      "Finchley Central",
      "East Finchley",
      "Highgate",
      "Archway",
      "Tufnell Park",
      "Kentish Town",
      "Camden Town",
      "Euston",
      "King's Cross St Pancras"
     ]
    ],
    "W": [
     [
      "Clapham North",
      "Stockwell",
      "Oval",
      "Kennington",
      "Elephant & Castle",
      "Borough",
      "London Bridge",
      "Bank",
      "Moorgate",
      "Old Street",
      "Angel",
      "King's Cross St Pancras"
     ]
    ]
   },
   "short": "NOR",
   "dirs": {
    "E": {
     "label": "Southbound",
     "platform": [
      "southbound"
     ]
    },
    "W": {
     "label": "Northbound",
     "platform": [
      "northbound"
     ]
    }
   },
   "westWords": "edgware|high barnet|mill hill|camden|golders|archway|east finchley|burnt oak|colindale"
  },
  "victoria": {
   "name": "Victoria",
   "colour": {
    "light": "#20A4E0",
    "dark": "#38B6EE"
   },
   "train": {
    "light": "#0B6FA4",
    "dark": "#A6E0FA"
   },
   "approach": {
    "E": [
     [
      "Brixton",
      "Stockwell",
      "Vauxhall",
      "Pimlico",
      "Victoria",
      "Green Park",
      "Oxford Circus",
      "Warren Street",
      "Euston",
      "King's Cross St. Pancras"
     ]
    ],
    "W": [
     [
      "Walthamstow Central",
      "Blackhorse Road",
      "Tottenham Hale",
      "Seven Sisters",
      "Finsbury Park",
      "Highbury & Islington",
      "King's Cross St. Pancras"
     ]
    ]
   },
   "short": "VIC",
   "dirs": {
    "E": {
     "label": "Northbound",
     "platform": [
      "northbound"
     ]
    },
    "W": {
     "label": "Southbound",
     "platform": [
      "southbound"
     ]
    }
   },
   "westWords": "brixton|victoria|stockwell|pimlico|vauxhall|green park|oxford circus|warren street|euston"
  },
  "piccadilly": {
   "name": "Piccadilly",
   "colour": {
    "light": "#003688",
    "dark": "#4F7FD9"
   },
   "train": {
    "light": "#001F4D",
    "dark": "#BFD2F5"
   },
   "approach": {
    "E": [
     [
      "Earl's Court",
      "Gloucester Road",
      "South Kensington",
      "Knightsbridge",
      "Hyde Park Corner",
      "Green Park",
      "Piccadilly Circus",
      "Leicester Square",
      "Covent Garden",
      "Holborn",
      "Russell Square",
      "King's Cross St. Pancras"
     ]
    ],
    "W": [
     [
      "Oakwood",
      "Southgate",
      "Arnos Grove",
      "Bounds Green",
      "Wood Green",
      "Turnpike Lane",
      "Manor House",
      "Finsbury Park",
      "Arsenal",
      "Holloway Road",
      "Caledonian Road",
      "King's Cross St. Pancras"
     ]
    ]
   },
   "short": "PIC",
   "dirs": {
    "E": {
     "label": "Eastbound",
     "platform": [
      "eastbound"
     ]
    },
    "W": {
     "label": "Westbound",
     "platform": [
      "westbound"
     ]
    }
   },
   "westWords": "heathrow|uxbridge|rayners|northfields|ealing|acton|hounslow|hammersmith|south harrow|earl|leicester|holborn",
   "skip": [
    "Turnham Green",
    "Stamford Brook",
    "Ravenscourt Park",
    "West Kensington"
   ]
  }
 },
 "westWords": "heathrow|uxbridge|ealing|richmond|acton|hounslow|rayners|northfields|boston manor|osterley|turnham|chiswick|gunnersbury|kew|ravenscourt|stamford|hatton|south ealing",
 "facts": [
  {
   "tag": "History",
   "text": "The Metropolitan Railway opened King's Cross station on 10 January 1863, as one of the stations on the world's first underground railway."
  },
  {
   "tag": "History",
   "text": "The Piccadilly line platforms opened on 15 December 1906, and the Northern line ones (then the City & South London Railway) on 11 May 1907."
  },
  {
   "tag": "History",
   "text": "The Victoria line reached King's Cross on 1 December 1968, in the second phase of the line's opening."
  },
  {
   "tag": "Name",
   "text": "The tube station became King's Cross for St Pancras in 1927 and King's Cross St Pancras in 1933. The Metropolitan station kept its old name until October 1940."
  },
  {
   "tag": "History",
   "text": "After bomb damage, new sub-surface platforms opened on 14 March 1941, about 250 metres west of the original site."
  },
  {
   "tag": "Station",
   "text": "Six lines and eight platforms: Circle, Hammersmith & City, Metropolitan, Northern, Piccadilly and Victoria."
  },
  {
   "tag": "Station",
   "text": "The station has eleven entrances and four ticket halls. The Western Ticket Hall, under the St Pancras forecourt, opened on 26 May 2006."
  },
  {
   "tag": "Redevelopment",
   "text": "An £810 million upgrade in the 2000s roughly doubled the station's capacity, to more than 100,000 people a day."
  },
  {
   "tag": "Access",
   "text": "Ten new lifts made the whole station step-free."
  },
  {
   "tag": "Art",
   "text": "Tom Eckersley's tiles in the Victoria line seat recesses show a cross of crowns, a play on the name King's Cross."
  },
  {
   "tag": "Art",
   "text": "The stainless steel 'Full Circle' sculptures are by the artist Knut Henrik Henriksen."
  },
  {
   "tag": "Passengers",
   "text": "With 77.13 million entries and exits in 2024, King's Cross St Pancras was the second busiest station on the Underground."
  }
 ],
 "tracks": [
  [
   "circle",
   "hammersmith-city",
   "metropolitan"
  ],
  [
   "northern"
  ],
  [
   "victoria"
  ],
  [
   "piccadilly"
  ]
 ],
 "angles": [
  38,
  12,
  -35,
  -70
 ]
};
