// Station page data: Barons Court (District and Piccadilly). Generated by tools/make_station.py. Facts: Wikipedia, 'Barons Court tube station', fetched 9 Oct 2026.
window.UNDERCURRENT_LINE = {
 "id": "station-bsc",
 "kind": "station",
 "name": "Barons Court",
 "naptan": "940GZZLUBSC",
 "lines": {
  "district": {
   "name": "District",
   "colour": {
    "light": "#00782A",
    "dark": "#2FA85A"
   },
   "train": {
    "light": "#0A4D22",
    "dark": "#C9F0D6"
   },
   "approach": {
    "E": [
     [
      "Ealing Broadway",
      "Ealing Common",
      "Acton Town",
      "Chiswick Park",
      "Turnham Green",
      "Stamford Brook",
      "Ravenscourt Park",
      "Hammersmith",
      "Barons Court"
     ],
     [
      "Richmond",
      "Kew Gardens",
      "Gunnersbury",
      "Turnham Green",
      "Stamford Brook",
      "Ravenscourt Park",
      "Hammersmith",
      "Barons Court"
     ]
    ],
    "W": [
     [
      "Blackfriars",
      "Temple",
      "Embankment",
      "Westminster",
      "St. James's Park",
      "Victoria",
      "Sloane Square",
      "South Kensington",
      "Gloucester Road",
      "Earl's Court",
      "West Kensington",
      "Barons Court"
     ],
     [
      "Edgware Road",
      "Paddington",
      "Bayswater",
      "Notting Hill Gate",
      "High Street Kensington",
      "Earl's Court",
      "West Kensington",
      "Barons Court"
     ]
    ]
   },
   "short": "DIS",
   "dirs": {
    "E": {
     "label": "Eastbound",
     "platform": [
      "eastbound"
     ]
    },
    "W": {
     "label": "Westbound",
     "platform": [
      "westbound"
     ]
    }
   }
  },
  "piccadilly": {
   "name": "Piccadilly",
   "colour": {
    "light": "#003688",
    "dark": "#4F7FD9"
   },
   "train": {
    "light": "#001F4D",
    "dark": "#BFD2F5"
   },
   "approach": {
    "E": [
     [
      "Hounslow Central",
      "Hounslow East",
      "Osterley",
      "Boston Manor",
      "Northfields",
      "South Ealing",
      "Acton Town",
      "Turnham Green",
      "Stamford Brook",
      "Ravenscourt Park",
      "Hammersmith",
      "Barons Court"
     ],
     [
      "Sudbury Hill",
      "Sudbury Town",
      "Alperton",
      "Park Royal",
      "North Ealing",
      "Ealing Common",
      "Acton Town",
      "Turnham Green",
      "Stamford Brook",
      "Ravenscourt Park",
      "Hammersmith",
      "Barons Court"
     ]
    ],
    "W": [
     [
      "Holborn",
      "Covent Garden",
      "Leicester Square",
      "Piccadilly Circus",
      "Green Park",
      "Hyde Park Corner",
      "Knightsbridge",
      "South Kensington",
      "Gloucester Road",
      "Earl's Court",
      "West Kensington",
      "Barons Court"
     ]
    ]
   },
   "short": "PIC",
   "dirs": {
    "E": {
     "label": "Eastbound",
     "platform": [
      "eastbound"
     ]
    },
    "W": {
     "label": "Westbound",
     "platform": [
      "westbound"
     ]
    }
   },
   "skip": [
    "Turnham Green",
    "Stamford Brook",
    "Ravenscourt Park",
    "West Kensington"
   ]
  }
 },
 "westWords": "heathrow|uxbridge|ealing|richmond|acton|hounslow|rayners|northfields|boston manor|osterley|turnham|chiswick|gunnersbury|kew|ravenscourt|stamford|hatton|south ealing",
 "facts": [
  {
   "tag": "History",
   "text": "The District Railway opened Barons Court station on 9 October 1905, though its trains had been running through the site since 1874."
  },
  {
   "tag": "History",
   "text": "The Piccadilly line platforms opened on 15 December 1906, with the Great Northern, Piccadilly and Brompton Railway."
  },
  {
   "tag": "Design",
   "text": "Harry Ford designed the station building, in a style close to his stations at Earl's Court and Hammersmith."
  },
  {
   "tag": "Design",
   "text": "The single-storey building mixes Classical and Art Nouveau styles and keeps its terracotta facing and Art Nouveau lettering. It has been Grade II listed since 1985."
  },
  {
   "tag": "Station",
   "text": "The wooden platform benches, with the station name on enamelled panels along the back, are thought to be unique on the Underground."
  },
  {
   "tag": "Name",
   "text": "The name may come from the Baronscourt estate in County Tyrone, possibly through Sir William Palliser, who built part of the area. Unlike Earl's Court, it has no apostrophe."
  },
  {
   "tag": "Station",
   "text": "Four platforms on two islands: the Piccadilly line uses the inner tracks and the District the outer ones, so you can change line across the platform."
  },
  {
   "tag": "Station",
   "text": "It is the last open-air stop for eastbound Piccadilly line trains until Arnos Grove."
  },
  {
   "tag": "Neighbourhood",
   "text": "The Queen's Club, home of a major grass-court tennis tournament, is at the end of Palliser Road."
  },
  {
   "tag": "Passengers",
   "text": "Barons Court recorded about 5.48 million entries and exits in 2024, up from 5.24 million in 2023."
  }
 ],
 "angles": [
  -16,
  16
 ]
};
